import axios from "axios";
import { NextResponse } from "next/server";

const BASE_URL = 'http://localhost:4000/api';

export interface Quiz {
  quiz_id?: string;  // Optional, as it's generated by the server
  module_id: string;
  userPerformance: number;
  questionCount: number;
  questionTypes: string[];
  created_at?: string; // Optional, as it's generated by the server
}


// export const getQuizById = async (quizId: string) => {
//   try {
      // console.log(`Fetching quiz with ID: ${quizId}`);
//     const response = await axios.get(`${BASE_URL}/quizzes/${quizId}`);
//     return NextResponse.json(response.data); // Return the quiz data from the response
//   } catch (error) {
//     console.error('Error fetching quiz by ID:', error);
//     return NextResponse.json({ error: 'Failed to fetch quiz by ID' }); // Return error message
//   }
// };

export const getAllQuizzes  = async () => {
  try {
    const response = await axios.get(`${BASE_URL}/quizzes/quizzes`);
    return NextResponse.json(response.data);
  } catch (error) {
    console.error('Error fetching courses:', error);
    return NextResponse.json({ error: 'Failed to fetch courses' });
  }

};

export async function GET() {
  try {
    const response = await axios.get(`${BASE_URL}/quizzes/quizzes`);
    return NextResponse.json(response.data);
  } catch (error) {
    console.error('Error fetching quizzes:', error);
    return NextResponse.json({ error: 'Failed to fetch quizzes' }, { status: 500 });
  }
}

export const createQuiz = async (quizData: Quiz) => {
  const response = await fetch('${BASE_URL}/quizzes', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(quizData),
  });
  if (!response.ok) throw new Error('Failed to create quiz');
  return response.json();
};
